version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'icon_db'
      POSTGRES_USER: 'zazahaf'
      POSTGRES_PASSWORD: 'Al12'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: